# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               DO IT YOURSELF     
tagline:             'Lo técnico es político'
description:         '"Las formas modernas de hegemonía estan basadas en la mediación técnica de una diversidad de prácticas sociales, sea la producción o la medicina, la educación y el ejército, y en consecuencia, la democratización de nuestra sociedad requiere un cambio radical tanto técnico como político" reserved <a href="https://es.wikipedia.org/wiki/Andrew_Feenberg" target="_blank">Andrew Feemberg</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://pablol3on.hithub.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
